openapi: 3.0.1
info:
  title: es.gob.radarcovid.verification
  description: Verification Service
  termsOfService: https://radarcovid.covid19.gob.es/terms-of-service/use-conditions.html
  version: 1.0.2.RELEASE
servers:
- url: https://radarcovid.covid19.gob.es
paths:
  /generate:
    get:
      tags:
      - generation-controller
      summary: Provides n verification codes
      description: Generates n verification codes to be used by Autonomous Communities
        so they can provide codes to affected people (n <= 1000)
      operationId: getCodes
      parameters:
      - name: "n"
        in: query
        required: true
        schema:
          minimum: 1
          type: integer
          format: int32
      responses:
        "200":
          description: Codes generated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CodesResultDto'
        "403":
          description: Authentication error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponseDto'
        "500":
          description: Exception
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponseDto'
      security:
      - apiKeyAuth: []
  /verify/tan:
    post:
      tags:
      - verification-controller
      summary: Verify provided Tan
      description: The provided Tan is verified to be formerly issued by the verification
        server
      operationId: verifyTan
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TanDto'
        required: true
      responses:
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponseDto'
        "404":
          description: Tan could not be verified
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponseDto'
        "200":
          description: Tan is valid and formerly issued by the verification server
          content:
            application/json:
              schema:
                type: object
        "500":
          description: Exception
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponseDto'
  /verify/code:
    post:
      tags:
      - verification-controller
      summary: Verify provided Code
      description: The provided Code is verified to be formerly issued by the Health
        Authority
      operationId: verifyCode
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CodeDto'
        required: true
      responses:
        "200":
          description: Code is valid and formerly issued by the Health Authority
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponseDto'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponseDto'
        "404":
          description: Code could not be verified
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponseDto'
        "500":
          description: Exception
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponseDto'
components:
  schemas:
    CodesResultDto:
      required:
      - codes
      - signature
      - validUntil
      type: object
      properties:
        validUntil:
          pattern: yyyy-MM-dd'T'HH:mm:ss.SSSZ
          type: string
          description: Date in UTC until codes are valid
          format: date-time
        signature:
          type: string
          description: Server signature so client applications can verify the response
        codes:
          type: array
          description: List of codes
          items:
            type: string
            description: List of codes
    MessageResponseDto:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    TanDto:
      required:
      - tan
      type: object
      properties:
        tan:
          type: string
          description: Transaction Number Model (TAN)
      description: The Transaction Number (TAN) to be verified
    CodeDto:
      required:
      - code
      - date
      type: object
      properties:
        date:
          pattern: dd/MM/yyyy
          type: string
          description: Date the patient indicates that he/she is infected
          format: date-time
        code:
          pattern: "^\\d{12}$"
          type: string
          description: 12 digits validation code
      description: The Code to be verified
    TokenResponseDto:
      required:
      - token
      type: object
      properties:
        token:
          type: string
          description: Token JWT to be used by application once verification code
            has been validated
  securitySchemes:
    apiKeyAuth:
      type: apiKey
      name: X-RadarCovid-Authorization
      in: header
      scheme: bearer
      bearerFormat: JWT
